### ISSUE TITLE
Run CephFS VFS integration under SELinux `Enforcing` mode

### ISSUE THREAD

**Issue by anoopcs9** [samba-in-kubernetes/sit-environment#79]
Our current approach puts SELinux into `Permissive` mode when _vfs_ceph_ module is used for integration.

_[playbooks/ansible/roles/samba.setup/tasks/cephfs/main.yml](https://github.com/samba-in-kubernetes/sit-environment/blob/main/playbooks/ansible/roles/samba.setup/tasks/cephfs/main.yml)_:
```
    - name: Set selinux in permissive mode
      selinux:
        policy: targeted
        state: permissive
```

Investigate the possibility to run under SELinux `Enforcing` mode.
